# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{fluxx_grant}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Eric Hansen"]
  s.date = %q{2010-08-03}
  s.email = %q{fluxx@acesfconsulting.com}
  s.extra_rdoc_files = [
    "README.rdoc",
     "README.textile"
  ]
  s.files = [
    "app/controllers/application_controller.rb",
     "app/helpers/application_helper.rb",
     "config/routes.rb",
     "lib/fluxx_grant.rb",
     "lib/fluxx_grant/engine.rb",
     "lib/generators/fluxx_grant_migration/fluxx_grant_migration_generator.rb",
     "lib/generators/fluxx_grant_migration/templates/create_funding_sources.rb",
     "lib/generators/fluxx_grant_migration/templates/create_initiatives.rb",
     "lib/generators/fluxx_grant_migration/templates/create_letter_templates.rb",
     "lib/generators/fluxx_grant_migration/templates/create_programs.rb",
     "lib/generators/fluxx_grant_migration/templates/create_request_funding_sources.rb",
     "lib/generators/fluxx_grant_migration/templates/create_request_geo_states.rb",
     "lib/generators/fluxx_grant_migration/templates/create_request_letters.rb",
     "lib/generators/fluxx_grant_migration/templates/create_request_organizations.rb",
     "lib/generators/fluxx_grant_migration/templates/create_request_reports.rb",
     "lib/generators/fluxx_grant_migration/templates/create_request_transactions.rb",
     "lib/generators/fluxx_grant_migration/templates/create_request_users.rb",
     "lib/generators/fluxx_grant_migration/templates/create_requests.rb",
     "lib/generators/fluxx_grant_public/fluxx_grant_public_generator.rb",
     "lib/tasks.rb"
  ]
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Fluxx Grant Core}
  s.test_files = [
    "test/dummy/app/controllers/application_controller.rb",
     "test/dummy/app/helpers/application_helper.rb",
     "test/dummy/config/application.rb",
     "test/dummy/config/boot.rb",
     "test/dummy/config/environment.rb",
     "test/dummy/config/environments/development.rb",
     "test/dummy/config/environments/production.rb",
     "test/dummy/config/environments/test.rb",
     "test/dummy/config/initializers/backtrace_silencers.rb",
     "test/dummy/config/initializers/inflections.rb",
     "test/dummy/config/initializers/mime_types.rb",
     "test/dummy/config/initializers/secret_token.rb",
     "test/dummy/config/initializers/session_store.rb",
     "test/dummy/config/routes.rb",
     "test/dummy/db/migrate/20100803151248_fluxx_engine_create_realtime_updates_table.rb",
     "test/dummy/db/migrate/20100803151249_fluxx_engine_create_multi_element_groups.rb",
     "test/dummy/db/migrate/20100803151250_fluxx_engine_create_multi_element_values.rb",
     "test/dummy/db/migrate/20100803151251_fluxx_engine_create_multi_element_choices.rb",
     "test/dummy/db/migrate/20100803151252_fluxx_engine_create_client_stores.rb",
     "test/dummy/db/migrate/20100803151554_fluxx_crm_create_geo_countries.rb",
     "test/dummy/db/migrate/20100803151555_fluxx_crm_create_geo_states.rb",
     "test/dummy/db/migrate/20100803151556_fluxx_crm_create_geo_cities.rb",
     "test/dummy/db/migrate/20100803151557_fluxx_crm_create_model_documents.rb",
     "test/dummy/db/migrate/20100803151558_fluxx_crm_create_organizations.rb",
     "test/dummy/db/migrate/20100803151559_fluxx_crm_create_user_organizations.rb",
     "test/dummy/db/migrate/20100803151600_fluxx_crm_create_users.rb",
     "test/dummy/db/migrate/20100803151601_fluxx_crm_create_notes.rb",
     "test/dummy/db/migrate/20100803151602_fluxx_crm_create_favorites.rb",
     "test/dummy/db/migrate/20100803151603_fluxx_crm_create_groups.rb",
     "test/dummy/db/migrate/20100803151604_fluxx_crm_create_group_members.rb",
     "test/dummy/db/migrate/20100803151605_fluxx_crm_create_workflow_events.rb",
     "test/dummy/db/migrate/20100803152034_fluxx_grant_create_programs.rb",
     "test/dummy/db/migrate/20100803152035_fluxx_grant_create_funding_sources.rb",
     "test/dummy/db/migrate/20100803152036_fluxx_grant_create_initiatives.rb",
     "test/dummy/db/migrate/20100803152037_fluxx_grant_create_letter_templates.rb",
     "test/dummy/db/migrate/20100803152038_fluxx_grant_create_requests.rb",
     "test/dummy/db/migrate/20100803152039_fluxx_grant_create_request_letters.rb",
     "test/dummy/db/migrate/20100803152040_fluxx_grant_create_request_organizations.rb",
     "test/dummy/db/migrate/20100803152041_fluxx_grant_create_request_reports.rb",
     "test/dummy/db/migrate/20100803152042_fluxx_grant_create_request_transactions.rb",
     "test/dummy/db/migrate/20100803152043_fluxx_grant_create_request_funding_sources.rb",
     "test/dummy/db/migrate/20100803152044_fluxx_grant_create_request_users.rb",
     "test/dummy/db/migrate/20100803152045_fluxx_grant_create_request_geo_states.rb",
     "test/dummy/db/schema.rb",
     "test/fluxx_grant_test.rb",
     "test/integration/navigation_test.rb",
     "test/support/integration_case.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<fastercsv>, [">= 1.5.3"])
      s.add_runtime_dependency(%q<formtastic-rails3>, [">= 0.9.10.0"])
      s.add_runtime_dependency(%q<haml>, [">= 3"])
      s.add_development_dependency(%q<jsmin>, [">= 1.0.1"])
      s.add_development_dependency(%q<thin>, [">= 1.2.7"])
      s.add_development_dependency(%q<json>, [">= 1.4.3"])
    else
      s.add_dependency(%q<fastercsv>, [">= 1.5.3"])
      s.add_dependency(%q<formtastic-rails3>, [">= 0.9.10.0"])
      s.add_dependency(%q<haml>, [">= 3"])
      s.add_dependency(%q<jsmin>, [">= 1.0.1"])
      s.add_dependency(%q<thin>, [">= 1.2.7"])
      s.add_dependency(%q<json>, [">= 1.4.3"])
    end
  else
    s.add_dependency(%q<fastercsv>, [">= 1.5.3"])
    s.add_dependency(%q<formtastic-rails3>, [">= 0.9.10.0"])
    s.add_dependency(%q<haml>, [">= 3"])
    s.add_dependency(%q<jsmin>, [">= 1.0.1"])
    s.add_dependency(%q<thin>, [">= 1.2.7"])
    s.add_dependency(%q<json>, [">= 1.4.3"])
  end
end

