# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{fluxx_grant}
  s.version = "0.0.17"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Eric Hansen"]
  s.date = %q{2011-02-15}
  s.email = %q{fluxx@acesfconsulting.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.textile"
  ]
  s.files = [
    "app/controllers/admin_cards_controller.rb",
    "app/controllers/application_controller.rb",
    "app/controllers/dashboard_controller.rb",
    "app/controllers/fip_requests_controller.rb",
    "app/controllers/funding_source_allocations_controller.rb",
    "app/controllers/funding_sources_controller.rb",
    "app/controllers/grant_requests_controller.rb",
    "app/controllers/granted_requests_controller.rb",
    "app/controllers/initiatives_controller.rb",
    "app/controllers/modal_reports_controller.rb",
    "app/controllers/organizations_controller.rb",
    "app/controllers/programs_controller.rb",
    "app/controllers/project_requests_controller.rb",
    "app/controllers/projects_controller.rb",
    "app/controllers/reports/granted_requests/monthly_grants_count_report.rb",
    "app/controllers/reports/granted_requests/monthly_grants_money_report.rb",
    "app/controllers/reports/modal_reports/dollars_by_organization_report.rb",
    "app/controllers/reports/modal_reports/funding_allocations_by_program_report.rb",
    "app/controllers/reports/modal_reports/funding_allocations_by_time_report.rb",
    "app/controllers/reports/modal_reports/pipeline_report.rb",
    "app/controllers/reports/modal_reports/program_initiative_budget_report.rb",
    "app/controllers/request_evaluation_metrics_controller.rb",
    "app/controllers/request_funding_sources_controller.rb",
    "app/controllers/request_organizations_controller.rb",
    "app/controllers/request_programs_controller.rb",
    "app/controllers/request_reports_controller.rb",
    "app/controllers/request_transaction_funding_sources_controller.rb",
    "app/controllers/request_transactions_controller.rb",
    "app/controllers/request_users_controller.rb",
    "app/controllers/sub_initiatives_controller.rb",
    "app/controllers/sub_programs_controller.rb",
    "app/controllers/user_sessions_controller.rb",
    "app/controllers/users_controller.rb",
    "app/helpers/application_grant_helper.rb",
    "app/models/fip_request.rb",
    "app/models/funding_source.rb",
    "app/models/funding_source_allocation.rb",
    "app/models/grant_request.rb",
    "app/models/initiative.rb",
    "app/models/liquid_filters.rb",
    "app/models/organization.rb",
    "app/models/program.rb",
    "app/models/project.rb",
    "app/models/project_request.rb",
    "app/models/request.rb",
    "app/models/request_evaluation_metric.rb",
    "app/models/request_funding_source.rb",
    "app/models/request_geo_state.rb",
    "app/models/request_organization.rb",
    "app/models/request_program.rb",
    "app/models/request_report.rb",
    "app/models/request_transaction.rb",
    "app/models/request_transaction_funding_source.rb",
    "app/models/request_user.rb",
    "app/models/role_user.rb",
    "app/models/sub_initiative.rb",
    "app/models/sub_program.rb",
    "app/models/user.rb",
    "app/models/user_organization.rb",
    "app/models/user_session.rb",
    "app/models/workflow_event.rb",
    "app/stylesheets/theme/default/funnel.sass",
    "app/stylesheets/theme/default/style.sass",
    "app/views/admin_cards/_admin_card_show.html.haml",
    "app/views/admin_cards/_extra_admin.html.haml",
    "app/views/dashboard/index.html.haml",
    "app/views/doc_templates/grant_agreement_letter.html",
    "app/views/doc_templates/grant_award_letter.html",
    "app/views/fip_requests/_fip_request_filter.html.haml",
    "app/views/fip_requests/_fip_request_form.html.haml",
    "app/views/funding_source_allocations/_funding_source_allocation_form.html.haml",
    "app/views/funding_source_allocations/_funding_source_allocation_list.html.haml",
    "app/views/funding_source_allocations/_funding_source_allocation_show.html.haml",
    "app/views/funding_source_allocations/_list_funding_source_allocations.html.haml",
    "app/views/funding_source_allocations/_programs.html.haml",
    "app/views/funding_sources/_funding_source_form.html.haml",
    "app/views/funding_sources/_funding_source_list.html.haml",
    "app/views/funding_sources/_funding_source_show.html.haml",
    "app/views/funding_sources/_list_funding_sources.html.haml",
    "app/views/grant_requests/_approve_grant_details.html.haml",
    "app/views/grant_requests/_edit_request_program.html.haml",
    "app/views/grant_requests/_edit_request_report.html.haml",
    "app/views/grant_requests/_edit_request_transaction.html.haml",
    "app/views/grant_requests/_fiscal_org.html.haml",
    "app/views/grant_requests/_funnel.html.haml",
    "app/views/grant_requests/_funnel_footer.html.haml",
    "app/views/grant_requests/_grant_request_filter.html.haml",
    "app/views/grant_requests/_grant_request_form.html.haml",
    "app/views/grant_requests/_grant_request_list.html.haml",
    "app/views/grant_requests/_grant_request_show.html.haml",
    "app/views/grant_requests/_grant_request_show_relationships.html.haml",
    "app/views/grant_requests/_more_grant_request_filter.html.haml",
    "app/views/grant_requests/_org_lookup.html.haml",
    "app/views/grant_requests/_program.html.haml",
    "app/views/grant_requests/_program_org.html.haml",
    "app/views/grant_requests/_related_request.html.haml",
    "app/views/grant_requests/_request_became_grant.html.haml",
    "app/views/grant_requests/_secondary_programs.html.haml",
    "app/views/grant_requests/_view_states.html.haml",
    "app/views/granted_requests/_grant_request_list.html.haml",
    "app/views/granted_requests/_granted_request_filter.html.haml",
    "app/views/initiatives/_initiative_filter.html.haml",
    "app/views/initiatives/_initiative_form.html.haml",
    "app/views/initiatives/_initiative_list.html.haml",
    "app/views/initiatives/_initiative_show.html.haml",
    "app/views/insta/_list_actions.html.haml",
    "app/views/insta/_show_action_buttons.html.haml",
    "app/views/insta/_show_extra_buttons.html.haml",
    "app/views/layouts/application.html.haml",
    "app/views/layouts/printable_show.html.haml",
    "app/views/letter_templates/al_china_er.html.erb",
    "app/views/letter_templates/al_gos.html.erb",
    "app/views/letter_templates/al_multiyear.html.erb",
    "app/views/letter_templates/al_public_charity.html.erb",
    "app/views/letter_templates/al_us_er.html.erb",
    "app/views/letter_templates/ga_china_er.html.erb",
    "app/views/letter_templates/ga_gos.html.erb",
    "app/views/letter_templates/ga_multiyear.html.erb",
    "app/views/letter_templates/ga_public_charity.html.erb",
    "app/views/letter_templates/ga_us_er.html.erb",
    "app/views/modal_reports/_funding_year_and_program_filter.html.haml",
    "app/views/modal_reports/_modal_report_filter.html.haml",
    "app/views/modal_reports/_modal_report_list.html.haml",
    "app/views/modal_reports/_pipeline_filter.html.haml",
    "app/views/modal_reports/_program_initiative_budget_filter.html.haml",
    "app/views/notes/_note_list.html.haml",
    "app/views/organizations/_more_org_filter.html.haml",
    "app/views/organizations/_more_org_form.html.haml",
    "app/views/organizations/_organization_filter.html.haml",
    "app/views/organizations/_organization_form.html.haml",
    "app/views/organizations/_related_organization.html.haml",
    "app/views/programs/_program_filter.html.haml",
    "app/views/programs/_program_form.html.haml",
    "app/views/programs/_program_list.html.haml",
    "app/views/programs/_program_show.html.haml",
    "app/views/project_requests/_list_project_grants.html.haml",
    "app/views/project_requests/_list_project_requests.html.haml",
    "app/views/project_requests/_project_grant_add.html.haml",
    "app/views/project_requests/_project_grant_list.html.haml",
    "app/views/project_requests/_project_request_add.html.haml",
    "app/views/project_requests/_project_request_form.html.haml",
    "app/views/project_requests/_project_request_list.html.haml",
    "app/views/project_requests/_project_request_show.html.haml",
    "app/views/projects/_project_show.html.haml",
    "app/views/request_evaluation_metrics/_list_request_evaluation_metrics.html.haml",
    "app/views/request_evaluation_metrics/_request_evaluation_metrics_form.html.haml",
    "app/views/request_evaluation_metrics/_request_evaluation_metrics_list.html.haml",
    "app/views/request_evaluation_metrics/_request_evaluation_metrics_show.html.haml",
    "app/views/request_funding_sources/_list_request_funding_sources.html.haml",
    "app/views/request_funding_sources/_program_form.html.haml",
    "app/views/request_funding_sources/_request_funding_source_form.html.haml",
    "app/views/request_funding_sources/_request_funding_source_list.html.haml",
    "app/views/request_funding_sources/_request_funding_source_show.html.haml",
    "app/views/request_organizations/_list_request_organizations.html.haml",
    "app/views/request_organizations/_organization_add.html.haml",
    "app/views/request_organizations/_request_organization_form.html.haml",
    "app/views/request_organizations/_request_organization_list.html.haml",
    "app/views/request_organizations/_request_organization_show.html.haml",
    "app/views/request_programs/_request_program_form.html.haml",
    "app/views/request_programs/_request_program_list.html.haml",
    "app/views/request_programs/_request_program_show.html.haml",
    "app/views/request_reports/_list_item1.html.haml",
    "app/views/request_reports/_related_documents.html.haml",
    "app/views/request_reports/_request_report_filter.html.haml",
    "app/views/request_reports/_request_report_form.html.haml",
    "app/views/request_reports/_request_report_list.html.haml",
    "app/views/request_reports/_request_report_show.html.haml",
    "app/views/request_transaction_funding_sources/_request_transaction_funding_source_form.html.haml",
    "app/views/request_transaction_funding_sources/_request_transaction_funding_source_list.html.haml",
    "app/views/request_transaction_funding_sources/_request_transaction_funding_source_show.html.haml",
    "app/views/request_transactions/_more_trans_filter.html.haml",
    "app/views/request_transactions/_related_request_transactions.html.haml",
    "app/views/request_transactions/_request_transaction_filter.html.haml",
    "app/views/request_transactions/_request_transaction_form.html.haml",
    "app/views/request_transactions/_request_transaction_list.html.haml",
    "app/views/request_transactions/_request_transaction_show.html.haml",
    "app/views/request_users/_list_request_users.html.haml",
    "app/views/request_users/_request_user_form.html.haml",
    "app/views/request_users/_request_user_list.html.haml",
    "app/views/request_users/_request_user_show.html.haml",
    "app/views/request_users/_user_add.html.haml",
    "app/views/role_users/_role_user_form.html.haml",
    "app/views/sub_initiatives/_sub_initiative_filter.html.haml",
    "app/views/sub_initiatives/_sub_initiative_form.html.haml",
    "app/views/sub_initiatives/_sub_initiative_list.html.haml",
    "app/views/sub_initiatives/_sub_initiative_show.html.haml",
    "app/views/sub_programs/_sub_program_filter.html.haml",
    "app/views/sub_programs/_sub_program_form.html.haml",
    "app/views/sub_programs/_sub_program_list.html.haml",
    "app/views/sub_programs/_sub_program_show.html.haml",
    "app/views/user_sessions/new.html.haml",
    "app/views/users/_related_users.html.haml",
    "app/views/users/_user_filter.html.haml",
    "app/views/users/_user_form_header.html.haml",
    "config/routes.rb",
    "lib/extensions/cap_deploy.rb",
    "lib/extensions/controllers/fluxx_admin_cards_controller.rb",
    "lib/extensions/controllers/fluxx_common_requests_controller.rb",
    "lib/extensions/controllers/fluxx_fip_requests_controller.rb",
    "lib/extensions/controllers/fluxx_funding_source_allocations_controller.rb",
    "lib/extensions/controllers/fluxx_funding_sources_controller.rb",
    "lib/extensions/controllers/fluxx_grant_organizations_controller.rb",
    "lib/extensions/controllers/fluxx_grant_projects_controller.rb",
    "lib/extensions/controllers/fluxx_grant_requests_controller.rb",
    "lib/extensions/controllers/fluxx_grant_users_controller.rb",
    "lib/extensions/controllers/fluxx_granted_requests_controller.rb",
    "lib/extensions/controllers/fluxx_initiatives_controller.rb",
    "lib/extensions/controllers/fluxx_modal_reports_controller.rb",
    "lib/extensions/controllers/fluxx_programs_controller.rb",
    "lib/extensions/controllers/fluxx_project_requests_controller.rb",
    "lib/extensions/controllers/fluxx_request_evaluation_metrics_controller.rb",
    "lib/extensions/controllers/fluxx_request_funding_sources_controller.rb",
    "lib/extensions/controllers/fluxx_request_organizations_controller.rb",
    "lib/extensions/controllers/fluxx_request_programs_controller.rb",
    "lib/extensions/controllers/fluxx_request_reports_controller.rb",
    "lib/extensions/controllers/fluxx_request_transaction_funding_sources_controller.rb",
    "lib/extensions/controllers/fluxx_request_transactions_controller.rb",
    "lib/extensions/controllers/fluxx_request_users_controller.rb",
    "lib/extensions/controllers/fluxx_sub_initiatives_controller.rb",
    "lib/extensions/controllers/fluxx_sub_programs_controller.rb",
    "lib/extensions/gem_handler.rb",
    "lib/extensions/hgrant_rack.rb",
    "lib/extensions/models/fluxx_fip_request.rb",
    "lib/extensions/models/fluxx_funding_source.rb",
    "lib/extensions/models/fluxx_funding_source_allocation.rb",
    "lib/extensions/models/fluxx_grant_organization.rb",
    "lib/extensions/models/fluxx_grant_project.rb",
    "lib/extensions/models/fluxx_grant_request.rb",
    "lib/extensions/models/fluxx_grant_role_user.rb",
    "lib/extensions/models/fluxx_grant_user.rb",
    "lib/extensions/models/fluxx_grant_user_organization.rb",
    "lib/extensions/models/fluxx_grant_workflow_event.rb",
    "lib/extensions/models/fluxx_initiative.rb",
    "lib/extensions/models/fluxx_program.rb",
    "lib/extensions/models/fluxx_project_request.rb",
    "lib/extensions/models/fluxx_request.rb",
    "lib/extensions/models/fluxx_request_evaluation_metric.rb",
    "lib/extensions/models/fluxx_request_funding_source.rb",
    "lib/extensions/models/fluxx_request_geo_state.rb",
    "lib/extensions/models/fluxx_request_organization.rb",
    "lib/extensions/models/fluxx_request_program.rb",
    "lib/extensions/models/fluxx_request_report.rb",
    "lib/extensions/models/fluxx_request_transaction.rb",
    "lib/extensions/models/fluxx_request_transaction_funding_source.rb",
    "lib/extensions/models/fluxx_request_user.rb",
    "lib/extensions/models/fluxx_sub_initiative.rb",
    "lib/extensions/models/fluxx_sub_program.rb",
    "lib/extensions/reports/funding_allocations_base_report.rb",
    "lib/extensions/reports/monthly_grants_base_report.rb",
    "lib/extensions/reports/pipeline_base_report.rb",
    "lib/extensions/reports/report_utility.rb",
    "lib/extensions/test/fluxx_grant_blueprint.rb",
    "lib/extensions/test/fluxx_grant_test_helper.rb",
    "lib/fluxx_grant.rb",
    "lib/fluxx_grant/engine.rb",
    "lib/generators/fluxx_grant_migration/fluxx_grant_migration_generator.rb",
    "lib/generators/fluxx_grant_migration/templates/add_bank_account_to_transaction.rb",
    "lib/generators/fluxx_grant_migration/templates/add_board_authority_to_request_funding_source.rb",
    "lib/generators/fluxx_grant_migration/templates/add_description_to_project_relationships.rb",
    "lib/generators/fluxx_grant_migration/templates/add_grant_fields_to_organization.rb",
    "lib/generators/fluxx_grant_migration/templates/add_new_fields_to_funding_source.rb",
    "lib/generators/fluxx_grant_migration/templates/add_payee_to_request_transaction.rb",
    "lib/generators/fluxx_grant_migration/templates/add_program_geo_zone_meg.rb",
    "lib/generators/fluxx_grant_migration/templates/add_retired_to_program_etc.rb",
    "lib/generators/fluxx_grant_migration/templates/add_spending_year_to_funding_source_allocation.rb",
    "lib/generators/fluxx_grant_migration/templates/add_sub_initiative_program_to_request_funding_source.rb",
    "lib/generators/fluxx_grant_migration/templates/create_funding_source_allocation.rb",
    "lib/generators/fluxx_grant_migration/templates/create_funding_sources.rb",
    "lib/generators/fluxx_grant_migration/templates/create_initiatives.rb",
    "lib/generators/fluxx_grant_migration/templates/create_letter_templates.rb",
    "lib/generators/fluxx_grant_migration/templates/create_programs.rb",
    "lib/generators/fluxx_grant_migration/templates/create_project_requests.rb",
    "lib/generators/fluxx_grant_migration/templates/create_request_evaluation_metrics.rb",
    "lib/generators/fluxx_grant_migration/templates/create_request_funding_sources.rb",
    "lib/generators/fluxx_grant_migration/templates/create_request_geo_states.rb",
    "lib/generators/fluxx_grant_migration/templates/create_request_letters.rb",
    "lib/generators/fluxx_grant_migration/templates/create_request_organizations.rb",
    "lib/generators/fluxx_grant_migration/templates/create_request_program.rb",
    "lib/generators/fluxx_grant_migration/templates/create_request_reports.rb",
    "lib/generators/fluxx_grant_migration/templates/create_request_transaction_funding_source.rb",
    "lib/generators/fluxx_grant_migration/templates/create_request_transactions.rb",
    "lib/generators/fluxx_grant_migration/templates/create_request_users.rb",
    "lib/generators/fluxx_grant_migration/templates/create_requests.rb",
    "lib/generators/fluxx_grant_migration/templates/create_sub_initiative.rb",
    "lib/generators/fluxx_grant_migration/templates/create_sub_program.rb",
    "lib/generators/fluxx_grant_migration/templates/drop_request_letters.rb",
    "lib/generators/fluxx_grant_migration/templates/limit_allocation_program_designation_to_one_field.rb",
    "lib/generators/fluxx_grant_migration/templates/make_eval_metrics_fields_text.rb",
    "lib/generators/fluxx_grant_migration/templates/populate_funding_source_allocations.rb",
    "lib/generators/fluxx_grant_migration/templates/switch_around_program_initiative_etc.rb",
    "lib/generators/fluxx_grant_migration/templates/switch_request_funding_source_authorities_to_allocation.rb",
    "lib/generators/fluxx_grant_public/fluxx_grant_public_generator.rb",
    "lib/generators/fluxx_grant_seed/fluxx_grant_seed_generator.rb",
    "lib/tasks.rb",
    "public/images/theme/default/funnel/arrow-tip.png",
    "public/images/theme/default/funnel/arrow.png",
    "public/javascripts/README.txt",
    "public/stylesheets/README.txt"
  ]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Fluxx Grant Core}
  s.test_files = [
    "test/blueprint.rb",
    "test/dummy/app/controllers/application_controller.rb",
    "test/dummy/app/helpers/application_helper.rb",
    "test/dummy/config/application.rb",
    "test/dummy/config/boot.rb",
    "test/dummy/config/environment.rb",
    "test/dummy/config/environments/development.rb",
    "test/dummy/config/environments/production.rb",
    "test/dummy/config/environments/test.rb",
    "test/dummy/config/initializers/backtrace_silencers.rb",
    "test/dummy/config/initializers/inflections.rb",
    "test/dummy/config/initializers/mime_types.rb",
    "test/dummy/config/initializers/secret_token.rb",
    "test/dummy/config/initializers/session_store.rb",
    "test/dummy/config/routes.rb",
    "test/dummy/db/migrate/20100803151248_fluxx_engine_create_realtime_updates_table.rb",
    "test/dummy/db/migrate/20100803151249_fluxx_engine_create_multi_element_groups.rb",
    "test/dummy/db/migrate/20100803151250_fluxx_engine_create_multi_element_values.rb",
    "test/dummy/db/migrate/20100803151251_fluxx_engine_create_multi_element_choices.rb",
    "test/dummy/db/migrate/20100803151252_fluxx_engine_create_client_stores.rb",
    "test/dummy/db/migrate/20100803151554_fluxx_crm_create_geo_countries.rb",
    "test/dummy/db/migrate/20100803151555_fluxx_crm_create_geo_states.rb",
    "test/dummy/db/migrate/20100803151556_fluxx_crm_create_geo_cities.rb",
    "test/dummy/db/migrate/20100803151557_fluxx_crm_create_model_documents.rb",
    "test/dummy/db/migrate/20100803151558_fluxx_crm_create_organizations.rb",
    "test/dummy/db/migrate/20100803151559_fluxx_crm_create_user_organizations.rb",
    "test/dummy/db/migrate/20100803151600_fluxx_crm_create_users.rb",
    "test/dummy/db/migrate/20100803151601_fluxx_crm_create_notes.rb",
    "test/dummy/db/migrate/20100803151602_fluxx_crm_create_favorites.rb",
    "test/dummy/db/migrate/20100803151603_fluxx_crm_create_groups.rb",
    "test/dummy/db/migrate/20100803151604_fluxx_crm_create_group_members.rb",
    "test/dummy/db/migrate/20100803151605_fluxx_crm_create_workflow_events.rb",
    "test/dummy/db/migrate/20100803152034_fluxx_grant_create_programs.rb",
    "test/dummy/db/migrate/20100803152035_fluxx_grant_create_funding_sources.rb",
    "test/dummy/db/migrate/20100803152036_fluxx_grant_create_initiatives.rb",
    "test/dummy/db/migrate/20100803152037_fluxx_grant_create_letter_templates.rb",
    "test/dummy/db/migrate/20100803152038_fluxx_grant_create_requests.rb",
    "test/dummy/db/migrate/20100803152039_fluxx_grant_create_request_letters.rb",
    "test/dummy/db/migrate/20100803152040_fluxx_grant_create_request_organizations.rb",
    "test/dummy/db/migrate/20100803152041_fluxx_grant_create_request_reports.rb",
    "test/dummy/db/migrate/20100803152042_fluxx_grant_create_request_transactions.rb",
    "test/dummy/db/migrate/20100803152043_fluxx_grant_create_request_funding_sources.rb",
    "test/dummy/db/migrate/20100803152044_fluxx_grant_create_request_users.rb",
    "test/dummy/db/migrate/20100803152045_fluxx_grant_create_request_geo_states.rb",
    "test/dummy/db/migrate/20100806151108_fluxx_grant_add_grant_fields_to_organization.rb",
    "test/dummy/db/migrate/20100809090857_acts_as_audited_migration.rb",
    "test/dummy/db/migrate/20100819101944_fluxx_crm_create_role_users.rb",
    "test/dummy/db/migrate/20101018233010_fluxx_crm_create_geo_regions.rb",
    "test/dummy/db/migrate/20101018233011_fluxx_crm_create_documents.rb",
    "test/dummy/db/migrate/20101018233051_fluxx_grant_create_request_evaluation_metrics.rb",
    "test/dummy/db/migrate/20101021202928_fluxx_crm_create_user_profiles.rb",
    "test/dummy/db/migrate/20101021202929_fluxx_crm_create_user_profile_rules.rb",
    "test/dummy/db/migrate/20101025182306_fluxx_crm_add_allowed_field_to_profile_rules.rb",
    "test/dummy/db/migrate/20101025182307_fluxx_crm_create_model_document_type.rb",
    "test/dummy/db/migrate/20101101232701_fluxx_crm_create_projects.rb",
    "test/dummy/db/migrate/20101101232702_fluxx_crm_create_project_lists.rb",
    "test/dummy/db/migrate/20101101232703_fluxx_crm_create_project_list_items.rb",
    "test/dummy/db/migrate/20101101232704_fluxx_crm_create_project_organizations.rb",
    "test/dummy/db/migrate/20101101232705_fluxx_crm_create_project_users.rb",
    "test/dummy/db/migrate/20101101232706_fluxx_crm_create_wiki_documents.rb",
    "test/dummy/db/migrate/20101101232752_fluxx_grant_create_project_requests.rb",
    "test/dummy/db/migrate/20101122185224_fluxx_grant_drop_request_letters.rb",
    "test/dummy/db/migrate/20101122221346_fluxx_crm_create_wiki_document_templates.rb",
    "test/dummy/db/migrate/20101123002112_add_authlogic_to_user.rb",
    "test/dummy/db/migrate/20101123021307_fluxx_crm_add_description_to_project_relationships.rb",
    "test/dummy/db/migrate/20101123021536_fluxx_grant_add_description_to_project_relationships.rb",
    "test/dummy/db/migrate/20101127174221_fluxx_crm_create_model_document_templates.rb",
    "test/dummy/db/migrate/20101202004553_fluxx_crm_remove_deleted_at_from_user_organizations.rb",
    "test/dummy/db/migrate/20101208182240_fluxx_grant_add_board_authority_to_request_funding_source.rb",
    "test/dummy/db/migrate/20101208192056_fluxx_grant_create_sub_program.rb",
    "test/dummy/db/migrate/20101208194137_fluxx_grant_create_sub_initiative.rb",
    "test/dummy/db/migrate/20101208215651_fluxx_grant_add_sub_initiative_program_to_request_funding_source.rb",
    "test/dummy/db/migrate/20101215231237_fluxx_grant_add_new_fields_to_funding_source.rb",
    "test/dummy/db/migrate/20101215231239_fluxx_grant_switch_around_program_initiative_etc.rb",
    "test/dummy/db/migrate/20101215232013_fluxx_grant_create_funding_source_allocation.rb",
    "test/dummy/db/migrate/20101220050809_fluxx_grant_switch_request_funding_source_authorities_to_allocation.rb",
    "test/dummy/db/migrate/20101220170429_fluxx_grant_populate_funding_source_allocations.rb",
    "test/dummy/db/migrate/20101222195540_fluxx_crm_user_add_column_for_test_user_flag.rb",
    "test/dummy/db/migrate/20110107223330_fluxx_grant_add_program_geo_zone_meg.rb",
    "test/dummy/db/migrate/20110108181208_fluxx_grant_create_request_program.rb",
    "test/dummy/db/migrate/20110109040916_fluxx_grant_add_retired_to_program_etc.rb",
    "test/dummy/db/migrate/20110110215335_fluxx_crm_add_fields_to_organization.rb",
    "test/dummy/db/migrate/20110113174511_fluxx_grant_add_spending_year_to_funding_source_allocation.rb",
    "test/dummy/db/migrate/20110114213334_fluxx_grant_limit_allocation_program_designation_to_one_field.rb",
    "test/dummy/db/migrate/20110118200058_fluxx_grant_create_request_transaction_funding_source.rb",
    "test/dummy/db/migrate/20110118200059_fluxx_grant_add_payee_to_request_transaction.rb",
    "test/dummy/db/migrate/20110124213130_fluxx_crm_create_bank_account.rb",
    "test/dummy/db/migrate/20110124213141_fluxx_grant_add_bank_account_to_transaction.rb",
    "test/dummy/db/migrate/20110128052701_fluxx_crm_create_work_task.rb",
    "test/dummy/db/migrate/20110130003908_fluxx_crm_add_worktask_completed_at_date.rb",
    "test/dummy/db/migrate/20110201004538_fluxx_grant_make_eval_metrics_fields_text.rb",
    "test/dummy/db/migrate/20110211010944_fluxx_crm_create_role.rb",
    "test/dummy/db/migrate/20110213073108_fluxx_crm_create_user_permission.rb",
    "test/dummy/db/schema.rb",
    "test/dummy/db/seeds.rb",
    "test/fluxx_grant_test.rb",
    "test/functional/admin_cards_controller_test.rb",
    "test/functional/fip_requests_controller_test.rb",
    "test/functional/funding_source_allocations_controller_test.rb",
    "test/functional/funding_sources_controller_test.rb",
    "test/functional/grant_requests_controller_test.rb",
    "test/functional/granted_requests_controller_test.rb",
    "test/functional/modal_reports_controller_test.rb",
    "test/functional/project_requests_controller_test.rb",
    "test/functional/projects_controller_test.rb",
    "test/functional/request_evaluation_metrics_controller_test.rb",
    "test/functional/request_funding_sources_controller_test.rb",
    "test/functional/request_organizations_controller_test.rb",
    "test/functional/request_programs_controller_test.rb",
    "test/functional/request_reports_controller_test.rb",
    "test/functional/request_transaction_funding_sources_controller_test.rb",
    "test/functional/request_transactions_controller_test.rb",
    "test/functional/request_users_controller_test.rb",
    "test/functional/role_users_controller_test.rb",
    "test/functional/sub_initiatives_controller_test.rb",
    "test/functional/sub_programs_controller_test.rb",
    "test/functional/users_controller_test.rb",
    "test/integration/navigation_test.rb",
    "test/support/integration_case.rb",
    "test/test_helper.rb",
    "test/unit/funding_source_allocation_test.rb",
    "test/unit/models/funding_source_test.rb",
    "test/unit/models/grant_request_test.rb",
    "test/unit/models/initiative_test.rb",
    "test/unit/models/organization_test.rb",
    "test/unit/models/program_test.rb",
    "test/unit/models/project_request_test.rb",
    "test/unit/models/request_funding_source_test.rb",
    "test/unit/models/request_geo_state_test.rb",
    "test/unit/models/request_organization_test.rb",
    "test/unit/models/request_report_test.rb",
    "test/unit/models/request_transaction_test.rb",
    "test/unit/models/request_user_test.rb",
    "test/unit/request_program_test.rb",
    "test/unit/request_transaction_funding_source_test.rb",
    "test/unit/sub_initiative_test.rb",
    "test/unit/sub_program_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, ["= 3.0.3"])
      s.add_runtime_dependency(%q<capybara>, ["= 0.3.7"])
      s.add_runtime_dependency(%q<sqlite3-ruby>, [">= 0"])
      s.add_runtime_dependency(%q<formtastic>, ["~> 1.1.0"])
      s.add_runtime_dependency(%q<haml>, [">= 3"])
      s.add_runtime_dependency(%q<will_paginate>, ["~> 3.0.pre2"])
      s.add_runtime_dependency(%q<fluxx_engine>, [">= 0.0.7"])
      s.add_runtime_dependency(%q<fluxx_crm>, [">= 0.0.4"])
      s.add_runtime_dependency(%q<jsmin>, [">= 1.0.1"])
      s.add_runtime_dependency(%q<thin>, [">= 1.2.7"])
      s.add_runtime_dependency(%q<machinist>, [">= 1.0.6"])
      s.add_runtime_dependency(%q<faker>, [">= 0.3.1"])
      s.add_runtime_dependency(%q<rcov>, [">= 0"])
      s.add_runtime_dependency(%q<thinking-sphinx>, [">= 2.0.2"])
      s.add_runtime_dependency(%q<delayed_job>, [">= 0"])
      s.add_runtime_dependency(%q<ts-delayed-delta>, [">= 1.1.0"])
      s.add_runtime_dependency(%q<paperclip>, [">= 0"])
      s.add_runtime_dependency(%q<authlogic>, [">= 0"])
      s.add_runtime_dependency(%q<aasm>, ["= 2.2.0"])
      s.add_runtime_dependency(%q<acts_as_audited_rails3>, [">= 1.1.2"])
      s.add_runtime_dependency(%q<paperclip>, [">= 0"])
      s.add_runtime_dependency(%q<mysql>, [">= 0"])
      s.add_runtime_dependency(%q<compass>, [">= 0"])
      s.add_runtime_dependency(%q<liquid>, [">= 0"])
      s.add_runtime_dependency(%q<writeexcel>, [">= 0.6.1"])
    else
      s.add_dependency(%q<rails>, ["= 3.0.3"])
      s.add_dependency(%q<capybara>, ["= 0.3.7"])
      s.add_dependency(%q<sqlite3-ruby>, [">= 0"])
      s.add_dependency(%q<formtastic>, ["~> 1.1.0"])
      s.add_dependency(%q<haml>, [">= 3"])
      s.add_dependency(%q<will_paginate>, ["~> 3.0.pre2"])
      s.add_dependency(%q<fluxx_engine>, [">= 0.0.7"])
      s.add_dependency(%q<fluxx_crm>, [">= 0.0.4"])
      s.add_dependency(%q<jsmin>, [">= 1.0.1"])
      s.add_dependency(%q<thin>, [">= 1.2.7"])
      s.add_dependency(%q<machinist>, [">= 1.0.6"])
      s.add_dependency(%q<faker>, [">= 0.3.1"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<thinking-sphinx>, [">= 2.0.2"])
      s.add_dependency(%q<delayed_job>, [">= 0"])
      s.add_dependency(%q<ts-delayed-delta>, [">= 1.1.0"])
      s.add_dependency(%q<paperclip>, [">= 0"])
      s.add_dependency(%q<authlogic>, [">= 0"])
      s.add_dependency(%q<aasm>, ["= 2.2.0"])
      s.add_dependency(%q<acts_as_audited_rails3>, [">= 1.1.2"])
      s.add_dependency(%q<paperclip>, [">= 0"])
      s.add_dependency(%q<mysql>, [">= 0"])
      s.add_dependency(%q<compass>, [">= 0"])
      s.add_dependency(%q<liquid>, [">= 0"])
      s.add_dependency(%q<writeexcel>, [">= 0.6.1"])
    end
  else
    s.add_dependency(%q<rails>, ["= 3.0.3"])
    s.add_dependency(%q<capybara>, ["= 0.3.7"])
    s.add_dependency(%q<sqlite3-ruby>, [">= 0"])
    s.add_dependency(%q<formtastic>, ["~> 1.1.0"])
    s.add_dependency(%q<haml>, [">= 3"])
    s.add_dependency(%q<will_paginate>, ["~> 3.0.pre2"])
    s.add_dependency(%q<fluxx_engine>, [">= 0.0.7"])
    s.add_dependency(%q<fluxx_crm>, [">= 0.0.4"])
    s.add_dependency(%q<jsmin>, [">= 1.0.1"])
    s.add_dependency(%q<thin>, [">= 1.2.7"])
    s.add_dependency(%q<machinist>, [">= 1.0.6"])
    s.add_dependency(%q<faker>, [">= 0.3.1"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<thinking-sphinx>, [">= 2.0.2"])
    s.add_dependency(%q<delayed_job>, [">= 0"])
    s.add_dependency(%q<ts-delayed-delta>, [">= 1.1.0"])
    s.add_dependency(%q<paperclip>, [">= 0"])
    s.add_dependency(%q<authlogic>, [">= 0"])
    s.add_dependency(%q<aasm>, ["= 2.2.0"])
    s.add_dependency(%q<acts_as_audited_rails3>, [">= 1.1.2"])
    s.add_dependency(%q<paperclip>, [">= 0"])
    s.add_dependency(%q<mysql>, [">= 0"])
    s.add_dependency(%q<compass>, [">= 0"])
    s.add_dependency(%q<liquid>, [">= 0"])
    s.add_dependency(%q<writeexcel>, [">= 0.6.1"])
  end
end

